title: herrmann.tech

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false

plugins:
  - jekyll-feed
  - jekyll-paginate

baseurl: /

# rss feed
feed:
  categories:
    - en
    - pt

# pagination
paginate: 6
paginate_path: /page:num/

# site wide translations
t:
  en:
    by: "by"
    when: "on"
    image: "image by"
  pt:
    by: "por"
    when: "em"
    image: "imagem"

