title: herrmann.tech

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false

baseurl: /

t:
  en:
    by: "by"
    when: "on"
    image: "image by"
  pt:
    by: "por"
    when: "em"
    image: "imagem"

