title: herrmann.tech

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false

plugins:
  - jekyll-feed
#  - jekyll-paginate

baseurl: /

# rss feed
feed:
  categories:
    - en
    - pt
    - es

# pagination
# paginate: 6
# paginate_path: /page:num/

# site wide translations
t:
  en:
    this_article: this article
    portrait: Augusto’s portrait
    bio:
      is a civic innovation practitioner engaged in finding ways to
      improve lives with the use of data. With a passion to open data,
      free software, the open and semantic web, data science, data
      engineering, machine learning and natural language processing,
      I've been involved in many interesting projects over the years,
      including designing and implementing collaboratively Brazil's
      national open data policy and portal, from 2010 to 2018.
    disclaimer:
      The views expressed on this article are those of the author only
      and do not necessarily represent the views of his employers and
      bear no direct relationship with his work.
    by: "by"
    when: "on"
    image: "image by"
    about_author: About the author
    licensing_preamble: The texts on this blog can be used according to the
    license_name: Creative Commons Attribution-ShareAlike 4.0 International
    license_href: https://creativecommons.org/licenses/by-sa/4.0/
    licensing_supplement: |
      license unless otherwise specified. Third party images may be either
      in the public domain, used with a permissive license or fair use or
      legal permission on citation and commentary.
    read_more: "read more"
    see_also: "See also"
    see_also_text:
      If you like this post, you might want to look at these too
    previous_post: "Previous post"
    next_post: "Next post"
    no_posts:
      There are no posts yet published in this language. Please check one
      of the other available languages.
    languages:
      en:
        code: en
        name: English
      pt:
        code: pt
        name: Portuguese
      es:
        code: es
        name: Spanish
    also_available: Also available in
  pt:
    this_article: este artigo
    portrait: retrato de Augusto
    bio:
      é um praticante da inovação cívica engajado em encontrar maneiras
      de melhorar vidas com o uso de dados. Apaixonado por dados
      abertos, software livre, a web aberta e semântica, ciência de
      dados, engenharia de dados, aprendizado de máquina e processamento
      de linguagem natural, estive envolvido em diversos projetos
      interessantes ao longo dos anos, incluindo projetar e implementar
      colaborativamente a política e o portal de dados abertos do
      governo federal brasileiro, de 2010 a 2018.
    disclaimer:
      As opiniões expressas neste artigo são apenas as do autor e não
      necessariamente representam as posições de seu empregador e nem
      trazem nenhuma relação direta com o seu trabalho.
    by: "por"
    when: "em"
    image: "imagem"
    about_author: Sobre o autor
    licensing_preamble:
      Os textos deste blog podem ser usados de acordo com a licença
    license_name: Creative Commons Atribuição-CompartilhaIgual 4.0 Internacional
    license_href: https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR
    licensing_supplement: |
      exceto quando especificado em contrário. Imagens de terceiros podem
      ou ser de domínio público, ou usam uma licença permissiva ou
      *fair use* ou permissão legal para citação e comentário.
    read_more: "leia mais"
    see_also: "Veja também"
    see_also_text:
      Se você gostou desta postagem, você pode querer ver essas também
    previous_post: "Texto anterior"
    next_post: "Próximo texto"
    no_posts:
      Ainda não há nenhuma postagem publicada neste idioma. Por favor verifique
      uma das outras línguas disponíveis.
    languages:
      en:
        code: en
        name: Inglês
      pt:
        code: pt
        name: Português
      es:
        code: es
        name: Espanhol
    also_available: Também disponível em
  es:
    this_article: este artículo
    portrait: retrato de Augusto
    bio:
      es un practicante de la innovación cívica comprometido en encontrar medios
      de mejorar vidas con el uso de datos. Ama los datos abiertos, software
      libre, la web abierta y semántica, ciencia de datos, ingeniaría de
      datos, aprendizaje de máquina y procesamiento de lenguaje natural,
      he estado involucrado en diversos proyectos interesantes al largo de los
      años, incluyendo proyectar y implementar colaborativamente la
      política y el portal de datos abiertos del gobierno federal brasileño,
      desde 2010 hasta 2018.
    disclaimer:
      Las opiniones expresas en este artigo son solas las del autor y
      no necesariamente corresponden a las posiciones de su empleador
      y no traen relación directa con su trabajo.
    by: "por"
    when: "en"
    image: "imagen"
    about_author: Sobre el autor
    licensing_preamble:
      Los textos de este blog pueden ser utilizados de acuerdo con la licencia
    license_name: Creative Commons Atribución-CompartaIgual 4.0 Internacional
    license_href: https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR
    licensing_supplement: excepto cuando de otra manera especificado.
    read_more: "lea más"
    see_also: "Vea también"
    see_also_text:
      Se te gusta esta entrada, puedes querer ver también estas
    previous_post: "Texto anterior"
    next_post: "Próximo texto"
    no_posts:
      No hay aún entradas disponibles en este idioma. Por favor verifique una
      de las otras lenguajes disponibles.
    languages:
      en:
        code: en
        name: Inglés
      pt:
        code: pt
        name: Portugués
      es:
        code: es
        name: Español
    also_available: También disponible en
